dependencies:
  override:
	- mkdir -p ~/.go_project/src/github.com/youturnmedia
	- ln -s ${HOME}/YouTurn.Web ${HOME}/.go_project/src/github.com/youturnmedia/YouTurn.Web
    # './...' is a relative pattern which means all subdirectories
    - curl https://glide.sh/get | sh      
    - sudo apt-get install apt-transport-https
    - curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -
    - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
    - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
    - sudo apt-get update && sudo apt-get install yarn
    - make install
    - make build
deployment:
  prod:
    branch: master
    heroku:
      appname: youturn-web
